### ISSUE TITLE
Compiler Error: cannot find library called CommonUtilities 

### ISSUE THREAD

**Issue by bdebruyn** [Azul3DInc/ClangToStringTemplate#1]
Errors from runinng the tool
```
Error executing cpp-gen.py
Error: /repo/CommonApplication/src/FileTransfer/include/FileTransfer/IClientTransfer.h:3:10: fatal error: 'CommonUtilities/NotifyMessage.h' file not found
#include "CommonUtilities/NotifyMessage.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Traceback (most recent call last):
  File "/home/ubuntu/.vim/bundle/cpp-gen/cpp-gen.py", line 91, in <module>
    main()
  File "/home/ubuntu/.vim/bundle/cpp-gen/cpp-gen.py", line 64, in main
    jsonStr = parser.parse(sourcePath, headerPath)
  File "/home/ubuntu/.vim/bundle/cpp-gen/py/parser.py", line 28, in parse
    raise Exception(errorMessage)
Exception: /repo/CommonApplication/src/FileTransfer/include/FileTransfer/IClientTransfer.h:3:10: fatal error: 'CommonUtilities/NotifyMessage.h' file not found
#include "CommonUtilities/NotifyMessage.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```
Here's the file contents:
```
#pragma once

#include "CommonUtilities/NotifyMessage.h"
#include "FileTransfer/FileTransferManifest.h"

namespace ft
{

   struct IClientTransfer
   {
      virtual void abort() = 0;
      virtual const msg::NotifyMessage transfer(const FileTransferManifest& manifest) = 0;
      virtual const msg::NotifyMessage open(const FileTransferManifest& manifest, msg::NotifyMessage& status) = 0;
      virtual const msg::NotifyMessage sendRequest(const FileTransferManifest& manifest, msg::NotifyMessage& status) = 0;
      virtual const msg::NotifyMessage sendFileContents(const FileTransferManifest& manifest, msg::NotifyMessage& status) = 0;
      virtual const msg::NotifyMessage receiveResponsePacketSize(msg::NotifyMessage& status) = 0;
      virtual const msg::NotifyMessage receiveResponse(msg::NotifyMessage& status) = 0;
   };

}
```

The library and headers are in a conan repo called Framwork. Verified it was in the cache. Cannot seem to find it, however.

**Comment by wyilio** [comment]
@bdebruyn Could you verify whether or not the include folder that includes `NotifyMessage.h` has an "-isystem" flag for the clang evocation in `compile_commands.json`? 
Should be right next to "file: /repo/CommonApplication/src/FileTransfer/src/IClientTransfer.cpp".

**Comment by bdebruyn** [comment]
I appears that the compile does not pick up the local paths from `-I` flags in the `compile_commands.json'.  It does appear to be picking up the `isystem` paths. Is there a reason for not pickup the `-I` paths? 

The work around is to use the ~/.vim/bundle/cpp-gen/config.json.
